#!/usr/bin/python3
"""Factorize as many numbers as possible
 into a product of two smaller numbers."""
import math
from sys import argv

def factorize(num):
    """"gets the factors of an integer > 1"""
    i = 2

    if num < 2:
        return
    print()
    print(num, "<- num-before")
    while num % i:
        i += 1
        print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))
        print(num, "<- num-after")
        print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            num = int(line.split('\n')[0])
            factorize(num)
            line = file.readline()
except:
    pass
