#!/usr/bin/python3
"""Factorize as many numbers as possible
 into a product of two smaller numbers."""
import math
from sys import argv

def factorize(num):
    """"gets the factors of an integer > 1"""
    i = 2

    if num < 2:
        return
    print()
    print(num, "<- num-before")
    while num % i:
        i += 1
        print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))
        print(num, "<- num-after")
        print()

if len(argv) != 2:
    exit()

def factors(filename):
    """read_file and prints them out"""

    with open(filename, encoding="utf-8") as file:
        for i in file.readlines():
            n = int(i)
            result = factory(n)


if __name__ == "__main__":
    factors(argv[1])
